// src/lib/audit/generate-document.ts
// Enclave Development branded website audit document generator
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  Header,
  Footer,
  AlignmentType,
  LevelFormat,
  HeadingLevel,
  BorderStyle,
  WidthType,
  ShadingType,
  PageNumber,
  PageBreak,
  convertInchesToTwip,
  ImageRun,
} from 'docx';
import * as fs from 'fs';
import * as path from 'path';
import type { AuditResults, CategoryScore } from './types';

// Enclave Development Brand Colors
const BRAND = {
  ORANGE: "E67E22",
  DARK: "1A1A1A",
  DARK_GRAY: "2C2C2C",
  MEDIUM_GRAY: "666666",
  LIGHT_GRAY: "999999",
  LIGHTER_GRAY: "CCCCCC",
  WHITE: "FFFFFF",
  SUCCESS: "27AE60",
  WARNING: "F39C12",
  DANGER: "E74C3C",
};

// Helper: Get score color
function getScoreColor(score: number): string {
  if (score >= 8) return BRAND.SUCCESS;
  if (score >= 6) return BRAND.WARNING;
  return BRAND.DANGER;
}

// Load logo image if available
function getLogoImage(): ImageRun | null {
  try {
    const logoPath = path.join(process.cwd(), 'public', 'logo-icon.png');
    if (fs.existsSync(logoPath)) {
      const logoBuffer = fs.readFileSync(logoPath);
      return new ImageRun({
        data: logoBuffer,
        transformation: { width: 60, height: 60 },
        type: 'png',
      });
    }
  } catch {
    // Logo not available, continue without it
  }
  return null;
}

// Helper: Get score label
function getScoreLabel(score: number): string {
  if (score >= 9) return "Excellent";
  if (score >= 7) return "Good";
  if (score >= 5) return "Needs Improvement";
  return "Critical Attention Required";
}

// Helper: Format date
function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }).format(date);
}

// Table styling
const tableBorder = { style: BorderStyle.SINGLE, size: 1, color: BRAND.LIGHTER_GRAY };
const cellBorders = { top: tableBorder, bottom: tableBorder, left: tableBorder, right: tableBorder };

export async function generateAuditDocument(
  auditResults: AuditResults,
  options?: { userName?: string }
): Promise<Buffer> {
  const {
    websiteUrl,
    overallScore,
    categories,
    topStrengths,
    criticalIssues,
    actionPlan,
    summary,
  } = auditResults;

  const generatedDate = new Date();
  const userName = options?.userName || 'Website Owner';
  const logo = getLogoImage();

  const doc = new Document({
    creator: "Enclave Development",
    title: `Website Audit Report - ${websiteUrl}`,
    description: "Professional website audit generated by Enclave Development",
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 }
        }
      },
      paragraphStyles: [
        {
          id: "Title",
          name: "Title",
          basedOn: "Normal",
          run: { size: 56, bold: true, color: BRAND.DARK, font: "Calibri Light" },
          paragraph: { spacing: { before: 0, after: 240 }, alignment: AlignmentType.CENTER }
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 32, bold: true, color: BRAND.ORANGE, font: "Calibri Light" },
          paragraph: { spacing: { before: 400, after: 200 } }
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 26, bold: true, color: BRAND.DARK, font: "Calibri" },
          paragraph: { spacing: { before: 320, after: 160 } }
        },
        {
          id: "Heading3",
          name: "Heading 3",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 24, bold: true, color: BRAND.DARK_GRAY, font: "Calibri" },
          paragraph: { spacing: { before: 240, after: 120 } }
        },
      ]
    },
    numbering: {
      config: [
        {
          reference: "bullet-list",
          levels: [{
            level: 0,
            format: LevelFormat.BULLET,
            text: "•",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 720, hanging: 360 } } }
          }]
        },
        {
          reference: "numbered-list",
          levels: [{
            level: 0,
            format: LevelFormat.DECIMAL,
            text: "%1.",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 720, hanging: 360 } } }
          }]
        },
      ]
    },
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1),
            right: convertInchesToTwip(1),
            bottom: convertInchesToTwip(1),
            left: convertInchesToTwip(1)
          }
        }
      },
      headers: {
        default: new Header({
          children: [new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [
              new TextRun({ text: "ENCLAVE DEVELOPMENT", bold: true, size: 18, color: BRAND.ORANGE }),
              new TextRun({ text: "  |  Website Audit Report", size: 18, color: BRAND.MEDIUM_GRAY })
            ]
          })]
        })
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: "Page ", size: 18, color: BRAND.MEDIUM_GRAY }),
              new TextRun({ children: [PageNumber.CURRENT], size: 18, color: BRAND.MEDIUM_GRAY }),
              new TextRun({ text: "  |  ", size: 18, color: BRAND.LIGHTER_GRAY }),
              new TextRun({ text: "enclavellc.net", size: 18, color: BRAND.ORANGE }),
              new TextRun({ text: "  |  ", size: 18, color: BRAND.LIGHTER_GRAY }),
              new TextRun({ text: "Web & Automation Services", size: 18, color: BRAND.MEDIUM_GRAY })
            ]
          })]
        })
      },
      children: [
        // === COVER PAGE ===
        new Paragraph({ spacing: { before: 800 } }),

        // Logo (if available)
        ...(logo ? [new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
          children: [logo]
        })] : []),

        // Company Name
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 120 },
          children: [new TextRun({ text: "ENCLAVE DEVELOPMENT", size: 36, bold: true, color: BRAND.ORANGE, font: "Calibri Light" })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
          children: [new TextRun({ text: "Web & Automation Services", size: 22, color: BRAND.MEDIUM_GRAY })]
        }),

        // Document Title
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 200, after: 120 },
          children: [new TextRun({ text: "WEBSITE AUDIT REPORT", size: 48, bold: true, color: BRAND.DARK, font: "Calibri Light" })]
        }),

        // Website URL
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
          children: [new TextRun({ text: websiteUrl, size: 26, color: BRAND.ORANGE })]
        }),

        // Overall Score Display
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 200 },
          children: [new TextRun({ text: "OVERALL SCORE", size: 22, bold: true, color: BRAND.MEDIUM_GRAY, allCaps: true })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 80 },
          children: [new TextRun({
            text: `${overallScore.toFixed(1)}/10`,
            size: 96,
            bold: true,
            color: getScoreColor(overallScore),
            font: "Calibri Light"
          })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
          children: [new TextRun({ text: getScoreLabel(overallScore), size: 28, color: getScoreColor(overallScore) })]
        }),

        // Meta info
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
          children: [new TextRun({ text: `Prepared for: ${userName}`, size: 22, color: BRAND.DARK_GRAY })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 80 },
          children: [new TextRun({ text: `Generated: ${formatDate(generatedDate)}`, size: 22, color: BRAND.MEDIUM_GRAY })]
        }),

        new Paragraph({ children: [new PageBreak()] }),

        // === EXECUTIVE SUMMARY ===
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun("Executive Summary")]
        }),
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun(summary || `This automated audit analyzed ${websiteUrl} across 8 key dimensions including visual design, user experience, mobile responsiveness, content quality, SEO, performance, accessibility, and security.`)]
        }),

        // Score Summary Table
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Score Breakdown")]
        }),
        generateScoreTable(categories),

        // Top Strengths
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Top Strengths")]
        }),
        ...topStrengths.map(s => new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [
            new TextRun({ text: s.title + ": ", bold: true }),
            new TextRun(s.description)
          ]
        })),

        // Critical Issues
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Priority Issues to Address")]
        }),
        ...criticalIssues.slice(0, 5).map(issue => new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          spacing: { after: 120 },
          children: [
            new TextRun({ text: issue.title + ": ", bold: true, color: BRAND.DANGER }),
            new TextRun({ text: issue.description, color: BRAND.DARK_GRAY })
          ]
        })),

        new Paragraph({ children: [new PageBreak()] }),

        // === DETAILED ANALYSIS ===
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun("Detailed Analysis")]
        }),
        ...generateCategoryAnalysis(categories),

        new Paragraph({ children: [new PageBreak()] }),

        // === ACTION PLAN ===
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun("Prioritized Action Plan")]
        }),

        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Quick Wins (This Week)")]
        }),
        ...(actionPlan?.quickWins || []).map(item => new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun(item)]
        })),

        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Short-Term (1-4 Weeks)")]
        }),
        ...(actionPlan?.shortTerm || []).map(item => new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun(item)]
        })),

        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("Strategic (1-3 Months)")]
        }),
        ...(actionPlan?.strategic || []).map(item => new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: item, color: BRAND.DARK_GRAY })]
        })),

        new Paragraph({ children: [new PageBreak()] }),

        // === NEXT STEPS / CTA ===
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun("Ready to Take Action?")]
        }),

        new Paragraph({
          spacing: { after: 280 },
          children: [new TextRun({
            text: "This audit gives you a clear picture of where your website stands. The next step is turning these insights into results.",
            size: 22,
            color: BRAND.DARK_GRAY
          })]
        }),

        // Services
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun("How Enclave Development Can Help")]
        }),

        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          spacing: { after: 120 },
          children: [
            new TextRun({ text: "Website Rebuild: ", bold: true, color: BRAND.ORANGE }),
            new TextRun({ text: "Modern, fast, mobile-first design that converts visitors into customers", color: BRAND.DARK_GRAY })
          ]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          spacing: { after: 120 },
          children: [
            new TextRun({ text: "Automation Setup: ", bold: true, color: BRAND.ORANGE }),
            new TextRun({ text: "Streamline your lead follow-up so you never miss an opportunity", color: BRAND.DARK_GRAY })
          ]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          spacing: { after: 120 },
          children: [
            new TextRun({ text: "Content & SEO: ", bold: true, color: BRAND.ORANGE }),
            new TextRun({ text: "Get found by the right customers with optimized content", color: BRAND.DARK_GRAY })
          ]
        }),
        new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          spacing: { after: 280 },
          children: [
            new TextRun({ text: "Ongoing Support: ", bold: true, color: BRAND.ORANGE }),
            new TextRun({ text: "Maintenance, updates, and continuous improvement", color: BRAND.DARK_GRAY })
          ]
        }),

        // CTA Box
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
          shading: { type: ShadingType.CLEAR, fill: "FEF3E7" },
          children: [new TextRun({ text: " ", size: 16 })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          shading: { type: ShadingType.CLEAR, fill: "FEF3E7" },
          children: [new TextRun({ text: "Schedule Your Free Consultation", size: 32, bold: true, color: BRAND.ORANGE })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 160 },
          shading: { type: ShadingType.CLEAR, fill: "FEF3E7" },
          children: [new TextRun({ text: "Let's discuss your audit results and create a plan tailored to your business.", size: 22, color: BRAND.DARK_GRAY })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          shading: { type: ShadingType.CLEAR, fill: "FEF3E7" },
          children: [
            new TextRun({ text: "Visit: ", size: 22, color: BRAND.DARK_GRAY }),
            new TextRun({ text: "enclavellc.net", size: 24, bold: true, color: BRAND.ORANGE }),
          ]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          shading: { type: ShadingType.CLEAR, fill: "FEF3E7" },
          children: [
            new TextRun({ text: "Email: ", size: 22, color: BRAND.DARK_GRAY }),
            new TextRun({ text: "n.garrett@enclavellc.net", size: 22, color: BRAND.ORANGE }),
          ]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          shading: { type: ShadingType.CLEAR, fill: "FEF3E7" },
          children: [new TextRun({ text: " ", size: 16 })]
        }),

        // Disclaimer
        new Paragraph({
          spacing: { before: 600 },
          children: [
            new TextRun({ text: "About This Report: ", bold: true, size: 18, color: BRAND.MEDIUM_GRAY }),
            new TextRun({
              text: "This automated audit analyzes publicly accessible content and provides a professional assessment of your website's current state. Scores are relative assessments based on industry best practices. For a comprehensive manual review with custom recommendations, contact us to schedule a consultation.",
              size: 18,
              color: BRAND.LIGHT_GRAY,
              italics: true
            })
          ]
        }),

        // Thank you
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 480 },
          children: [new TextRun({ text: "Thank you for choosing Enclave Development", size: 22, color: BRAND.MEDIUM_GRAY, italics: true })]
        }),
      ]
    }]
  });

  return await Packer.toBuffer(doc);
}

function generateScoreTable(categories: CategoryScore[]): Table {
  const headerRow = new TableRow({
    children: [
      new TableCell({
        shading: { fill: BRAND.ORANGE, type: ShadingType.CLEAR },
        width: { size: 50, type: WidthType.PERCENTAGE },
        children: [new Paragraph({
          children: [new TextRun({ text: "Category", bold: true, color: BRAND.WHITE, size: 22 })]
        })]
      }),
      new TableCell({
        shading: { fill: BRAND.ORANGE, type: ShadingType.CLEAR },
        width: { size: 25, type: WidthType.PERCENTAGE },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Score", bold: true, color: BRAND.WHITE, size: 22 })]
        })]
      }),
      new TableCell({
        shading: { fill: BRAND.ORANGE, type: ShadingType.CLEAR },
        width: { size: 25, type: WidthType.PERCENTAGE },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Status", bold: true, color: BRAND.WHITE, size: 22 })]
        })]
      }),
    ]
  });

  const dataRows = categories.map((cat, index) => new TableRow({
    children: [
      new TableCell({
        borders: cellBorders,
        shading: { fill: index % 2 === 0 ? "FFFFFF" : "F9F9F9", type: ShadingType.CLEAR },
        children: [new Paragraph({ children: [new TextRun({ text: cat.name, size: 22, color: BRAND.DARK })] })]
      }),
      new TableCell({
        borders: cellBorders,
        shading: { fill: index % 2 === 0 ? "FFFFFF" : "F9F9F9", type: ShadingType.CLEAR },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: `${cat.score}/10`,
            bold: true,
            size: 24,
            color: getScoreColor(cat.score)
          })]
        })]
      }),
      new TableCell({
        borders: cellBorders,
        shading: { fill: index % 2 === 0 ? "FFFFFF" : "F9F9F9", type: ShadingType.CLEAR },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: cat.status,
            size: 20,
            color: getScoreColor(cat.score)
          })]
        })]
      }),
    ]
  }));

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...dataRows]
  });
}

function generateCategoryAnalysis(categories: CategoryScore[]): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  for (const cat of categories) {
    // Category heading
    paragraphs.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [
        new TextRun(`${cat.name} `),
        new TextRun({
          text: `(${cat.score}/10 - ${cat.status})`,
          color: getScoreColor(cat.score)
        })
      ]
    }));

    // Findings
    if (cat.findings && cat.findings.length > 0) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun("What We Found")]
      }));

      for (const finding of cat.findings) {
        paragraphs.push(new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun(finding)]
        }));
      }
    }

    // Recommendations
    if (cat.recommendations && cat.recommendations.length > 0) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun("Recommendations")]
      }));

      for (const rec of cat.recommendations) {
        paragraphs.push(new Paragraph({
          numbering: { reference: "bullet-list", level: 0 },
          children: [new TextRun(rec)]
        }));
      }
    }
  }

  return paragraphs;
}
